version: "3.9"

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--providers.docker=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=anup.kablia@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/acme.json:/letsencrypt/acme.json"
    restart: always

  flask:
    build: ./flask
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.domjudge.rule=Host(`test.csbasics.in`)"
      - "traefik.http.routers.domjudge.entrypoints=websecure"
      - "traefik.http.routers.domjudge.tls.certresolver=myresolver"
    restart: always
